package GUI;

import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 * @author: Archie Gunasekara
 * @date: 2013.07.02
 */
public class DataTablePanel extends javax.swing.JPanel {

    private JTable jt;
    private JScrollPane scrollPane;
    private ArrayList<String> columnNames;
    private ArrayList<String[]> data;
    
    /**
     * Creates new form DataTablePanel
     */
    public DataTablePanel(ArrayList<String> columnNames, ArrayList<String[]> data) {
	initComponents();
	this.columnNames = columnNames;
	this.data = data;
	createTable();
    }
    
    public void createTable() {
	
	Object[][] arr = new Object[data.size()][columnNames.size()];
	
	for(int i = 0; i < arr.length; i++) {
	
	    arr[i] = (Object[])data.get(i);
	}
	
	String[] cols = new String[columnNames.size()];
	
	for(int i = 0; i < columnNames.size(); i++) {
	    
	    cols[i] = columnNames.get(i);
	}
	
	jt = new JTable(arr, cols);	
	scrollPane = new JScrollPane(jt);
	
	add(scrollPane);
	this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(470, 250));
        setMinimumSize(new java.awt.Dimension(470, 250));
        setPreferredSize(new java.awt.Dimension(470, 250));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridLayout(1, 0));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
