package GUI;

import DBTools.ConnectionTypes;
import MainApp.AppStateHolder;

/**
 * @author: Archie Gunasekara
 * @date: 2013.07.02
 */
public class DBServerSelector extends javax.swing.JPanel {
    
    private MainFrame mf;
    private AppStateHolder appState;
    
    /**
     * Creates new form DBServerSelector
     */
    public DBServerSelector(MainFrame mf, AppStateHolder appState) {
	initComponents();
	this.mf = mf;
	this.appState = appState;
	
	for(ConnectionTypes type : ConnectionTypes.values()) {
	    
	    serverType.addItem(type);
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        serverType = new javax.swing.JComboBox();
        selectionLabel = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        serverType.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        add(serverType, gridBagConstraints);

        selectionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectionLabel.setText("Please select a server type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        add(selectionLabel, gridBagConstraints);

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        add(continueButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed

	appState.setConnectionType(ConnectionTypes.valueOf(serverType.getSelectedItem().toString()));
	mf.showDatabaseSelector();
    }//GEN-LAST:event_continueButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel selectionLabel;
    private javax.swing.JComboBox serverType;
    // End of variables declaration//GEN-END:variables
}
